### ISSUE TITLE
Plots not appearing in Rstudio viewer

### ISSUE THREAD

**Issue by methodds** [mages/googleVis#12]
Hi,

I am using Linux Mint, R-Studio Version 0.98.1103 , R-Version 3.1.3 and googleVis 0.5.8. Plotting nonflash visualisations like tables never uses my Viewerpanel in R-Studio but instead the default browser.

Example Code:

data(mtcars)
gvt = gvisTable(mtcars)
plot(gvt)

Any idea why this is not working? I did not change any default options.

**Comment by mages** [comment]
Unfortunately this option is currently not available, as RStudio prevents access of external JavaScript libraries, such as Google Chart Tools. However, the situation may change again in the future, as mentioned in the release notes of googleVis 0.5.3: http://www.magesblog.com/2014/04/googlevis-051-released-on-cran.html
