### ISSUE TITLE
Shiny example doesn't generate graph

### ISSUE THREAD

**Issue by jpastore001** [mages/googleVis#18]
Using the example straight from your cran documentation, the following code generates a shiny dropdown but no graph.

I am able to plot the gvisScatterChart when i pass it variables not through shiny.

Seems to be something wrong with the renderGvis function?

# server.R
library(googleVis)
shinyServer(function(input, output) {
  datasetInput <- reactive({
    switch(input$dataset,
           "rock" = rock,
           "pressure" = pressure,
           "cars" = cars)
  })
  output$view <- renderGvis({
    gvisScatterChart(datasetInput(),
                     options=list(title=paste(Data:,input$dataset)))
  })
})

# ui.R
shinyUI(pageWithSidebar(
  headerPanel("googleVis on Shiny"),
  sidebarPanel(
    selectInput("dataset", "Choose a dataset:",
                choices = c("rock", "pressure", "cars"))
  ),
  mainPanel(
    htmlOutput("view")
  )
))

**Comment by mages** [comment]
Have you tried the following, which executes the same example and works for me:
```S
library(shiny)
runApp(system.file("shiny/", package="googleVis"))
```
Here is my session info:
```S
R version 3.2.0 (2015-04-16)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.3 (Yosemite)

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_0.11.1    googleVis_0.5.8

loaded via a namespace (and not attached):
[1] R6_2.0.1        htmltools_0.2.6 tools_3.2.0     Rcpp_0.11.6    
[5] RJSONIO_1.3-0   digest_0.6.8    xtable_1.7-4    httpuv_1.3.2   
[9] mime_0.3
```

**Comment by jpastore001** [comment]
That works.  But when I use the code I listed for server.r and ui.r it does
not work.

**Comment by mages** [comment]
I believe you forgot the speech marks around Data in the paste statement of the server.R file.
Compare your code against my example, which you find here: https://github.com/mages/googleVis/tree/master/inst/shiny

**Comment by jpastore001** [comment]
Cool.  That was it.  You may want to update your cran doc example code
accordingly.

Thanks for your help!
