### ISSUE TITLE
chart using ordered factors not shown, as the javascript is produced incorrectly

### ISSUE THREAD

**Issue by carsten-langer** [mages/googleVis#24]
When using ordered factor, a chart is not displayed, as the underlying javascript is not correct.

Using "factor" is ok and produces in the HTML/javascript two entries "data.addColumn" as expected.

HTML excerpt ok:
    data.addColumn('string','foo');
    data.addColumn('number','bar');
    data.addRows(datajson);

```{r}
require(googleVis)
df.ok <- data.frame(foo = factor(c("a", "c", "b")), bar = c(1, 6, 4))
plot(gvisColumnChart(df.ok))
```

But using "ordered" is __not ok__. The "data.addColumn" for the ordered factor is missing from the generated HTML/javascript. As result, the chart does not display.

HTML excerpt not ok:
    data.addColumn('number','bar');
    data.addRows(datajson);

```{r}
df.nok <- data.frame(foo = ordered(c("a", "c", "b")), bar = c(1, 6, 4))
plot(gvisColumnChart(df.nok))
```

Expectation is that a chart on data using `ordered` works the same as with `factor`.

**Comment by mages** [comment]
Thanks for reporting this issue. It was clearly a bug in our code. I believe I fixed the issue now. Could you please confirm with the developer version 0.5.10 on GitHub?

**Comment by carsten-langer** [comment]
It took a while until I understood how to test a github developer version inside knitr inside RStudio, but now I got that sorted out.
Yes, the bug ix fixed. Thank you.
