### ISSUE TITLE
Any plan to update googleVis to the new google chart

### ISSUE THREAD

**Issue by JianWang2016** [mages/googleVis#35]
With the recent release of google chart, I wonder if there is any plan to update googleVis?  Thanks.

**Comment by mages** [comment]
I haven't got much time at the moment. Which aspects are you referring to, and can you help?

**Comment by JianWang2016** [comment]
Hi Markus:  I just saw some new charts such as diff charts etc which are not included in googleVis and just wish you have thought about to incorporate them into googlevis at some point.  Thanks much. -Jian

https://developers.google.com/chart/interactive/docs/gallery/diffchart
https://developers.google.com/chart/interactive/docs/gallery/trendlines#changing-the-opacity-and-line-width
https://developers.google.com/chart/interactive/docs/gallery/intervals
