### ISSUE TITLE
gvisMotionChart why not allow xvar and yvar to be categorical?

### ISSUE THREAD

**Issue by ngduyhieu** [mages/googleVis#40]
Dear all,
gvisMotionChart is a great tool to visualise the data in R. However, why don't you make it work with categorical xvar and yvar as well? Of course, a hack is to convert them to 0, 1, 2, etc. But changing the x & y ticks is maddening hard (at least for a Java noob like me). It would be great if you can add in the feature. Thanks

**Comment by mages** [comment]
Hi there,
You have to raise this issue with Google. We only supply an R interface.
Thanks
