### ISSUE TITLE
gvisPieChart legend

### ISSUE THREAD

**Issue by JianWang2016** [mages/googleVis#43]
Dear Markus,
In the current release, legend = 'none' is ignored by the function and the plot would include legend even with legend = 'none'.  
data("CityPopularity")

pie <- gvisPieChart(CityPopularity,
             options=list(
               width=200,
               height=200,
               title='test',
               legend='none',
               colors="['orange', 'transparent']",
               pieSliceText='percentage',
               pieHole=0.5))
plot(pie)

**Comment by mages** [comment]
Hi there,
Looks like a bug was introduced with the move from RJSONIO to jsonlite. I believe I fixed it with version 0.6.1, now on GitHub. Can you please check.
Thanks
Markus

**Comment by JianWang2016** [comment]
Markus,  

Thanks much for the update.  Here is what I got:

> devtools::install_github("mages/googleVis")
Downloading github repo mages/googleVis@master
Installing googleVis
'/opt/R/R-3.2.0/lib64/R/bin/R' --vanilla CMD INSTALL  \
  '/lrlhps/data/digitalbiomarker/d1pam/junk/tmp/RtmpG71P1A/devtools29bae21abb0/mages-googleVis-7b9fae4' --library='/home/c085541/R_lib' --install-tests 

* installing *source* package ‘googleVis’ ...
** R
** data
*** moving datasets to lazyload DB
** demo
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Creating a generic function for ‘toJSON’ from package ‘jsonlite’ in package ‘googleVis’
* DONE (googleVis)
> library(googleVis)
Error in get(method, envir = home) : 
  lazy-load database '/home/c085541/R_lib/googleVis/R/googleVis.rdb' is corrupt
In addition: Warning messages:
1: In .registerS3method(fin[i, 1], fin[i, 2], fin[i, 3], fin[i, 4],  :
  restarting interrupted promise evaluation
2: In get(method, envir = home) :
  restarting interrupted promise evaluation
3: In get(method, envir = home) : internal error -3 in R_decompress1
Error: package or namespace load failed for ‘googleVis’

**Comment by mages** [comment]
That's strange, it works for me. Can you try again in a clean new R session.

**Comment by JianWang2016** [comment]
Markus:  I did, a couple of times.   Each time I download from mages<https://github.com/mages>/googleVis<https://github.com/mages/googleVis>
, I would encounter this error, and any package downloaded afterwards would encounter the same error.  I would start a new R session, other packages would succeed but the minute I go back to mages/googlevis, I would get this error again.

-Jian

**Comment by mages** [comment]
Can you send me an email with output of sessionInfo()? 

I can send you a binary version of the package for testing.

**Comment by JianWang2016** [comment]
Hi Markus:

                While preparing to get a clear R session, rerun the package download and send you my sessionInfo(), the download went smoothly without error.  Not sure what is amiss at my end.  But the great news is that the legend issue is resolved!

                Thank you so much for helping out.

-Jian

**Comment by JianWang2016** [comment]
Thank you very much.  All resolved!

**Comment by mages** [comment]
Great to hear that it is now working for you. Thanks for testing.

**Comment by mages** [comment]
Version 0.6.1 is now CRAN
