### ISSUE TITLE
Background not changing for gvisTimeline

### ISSUE THREAD

**Issue by DevangRamMohan** [mages/googleVis#44]
Hi,

I was trying to use the gvisTimeline function but was not able to get the background colour to change despite specifying the parameter as described in the example code in the documentation. It seems like backgroundColor is reaching the javascript end as an array (eg ['#000']) while it expects a string (eg '#000'). My reason for saying this is removing the square brackets in the corresponding html portion in tl$html$chart renders it perfectly. I'm not sure if I'm doing something wrong or if this is a known issue, just thought I would bring it up just in case it's helpful.

```
dat <- data.frame(Position=c(rep("President", 3), rep("Vice", 3)),
                  Name=c("Washington", "Adams", "Jefferson",
                         "Adams", "Jefferson", "Burr"),
                  start=as.Date(x=rep(c("1789-03-29", "1797-02-03", "1801-02-03"),2)),
                  end=as.Date(x=rep(c("1797-02-03", "1801-02-03", "1809-02-03"),2)))

tl <- gvisTimeline(data=dat, rowlabel="Name",barlabel="Position", 
                   start="start", end="end",
                   options=list(timeline="{groupByRowLabel:false}",
                                backgroundColor='#ffd', height=350,
                                colors="['#cbb69d', '#603913', '#c69c6e']"))

plot(tl)
```

**Comment by mages** [comment]
Hi there,
Looks like a bug was introduced with the move from RJSONIO to jsonlite. I believe I fixed it with version 0.6.1, now on GitHub. Can you please check.
Thanks
Markus

**Comment by DevangRamMohan** [comment]
Hi,

I tried it out and it worked perfectly. I had to do a "library(jsonlite)" before the above code chunk though because it couldn't find the function "unbox". Other than that, it worked like a charm. 

Thanks :)

**Comment by mages** [comment]
Perfect! I forgot to add unbox to NAMESPACE.
