### ISSUE TITLE
Sankey Out of Frame

### ISSUE THREAD

**Issue by BazilD** [mages/googleVis#47]
Hi, I'm relatively new to R and GoogleVis. I've recently discovered the gvissankey function however whenever I pull a chart the bottom half is always cut off/out of frame (See attached). Do you know how I can resolve this issue? also as the totals of each side of my sankey diagram are the same is it possible to make the start and finish level in height? finally how do you amend the node colours? Thanks, this is a fantastic package by the way!!! 

[SankeyID23e46ff57f27.pdf](https://github.com/mages/googleVis/files/501168/SankeyID23e46ff57f27.pdf)

**Comment by mages** [comment]
Have you tried setting the height? E.g:

```r
library(googleVis)
dat <- data.frame(From=c(rep("A",3), rep("B", 3)), 
                  To=c(rep(c("X", "Y", "Z"),2)), 
                  Weight=c(5,7,6,2,9,4))

sk1 <- gvisSankey(dat, from="From", to="To", weight="Weight",
                  options=list(height=600))
plot(sk1)
```

Otherwise, please send a minimal reproducible example.

**Comment by BazilD** [comment]
I did try height already and it just seems to make more of the diagram out of frame. see attached.

[SankeyID23e46d047b2.pdf](https://github.com/mages/googleVis/files/501231/SankeyID23e46d047b2.pdf)

**Comment by mages** [comment]
Please send a minimal reproducible example.

**Comment by BazilD** [comment]
Hi, i've attached my data and code. I can't for the life of me work out why it's not working :(

data <- read.csv(file.choose())
library(googleVis)
plot(gvisSankey(data,  from = data$from, to = data$to, weight = data$weight, options = list(height=400, width =                                                                                              "automatic")))

[Book1.txt](https://github.com/mages/googleVis/files/501623/Book1.txt)

**Comment by mages** [comment]
I think your weights are causing you the trouble. Some are 0, and other are really high.
Perhaps, you can consider a log scale. That seems to make sense to me and works:
```r
data <- read.csv("~/Downloads/Book1.txt", sep = "\t")
data$Weight[data$Weight == 0] <- 1
data$logWeight <- log(data$Weight)

summary(data$Weight)
summary(data$logWeight)

library(googleVis)
plot(gvisSankey(data=data, from = "From", to = "To", 
                weight = "logWeight", 
                options = list(height=400, width = "400")))

```

![screenshot](https://cloud.githubusercontent.com/assets/1146581/18971252/54a8d7da-868c-11e6-8959-75e7974e8bee.png)

**Comment by BazilD** [comment]
Cheers that's a good solution! do you know why google might not like the weights?

**Comment by mages** [comment]
Well, I think that a question for the guys at Google: https://groups.google.com/forum/#!forum/google-visualization-api
