### ISSUE TITLE
Bundle Annotations like Google Finance

### ISSUE THREAD

**Issue by stevenae** [mages/googleVis#49]
Hello,

Thank you for maintaining this invaluable project! I have a request -- Google Finance seems to use the same AnnotatedTimeLine function as googleVis, but their charts bundle multiple annotations for the same data point such that they are unintrusive:
![screen shot 2016-10-19 at 5 23 54 pm](https://cloud.githubusercontent.com/assets/759581/19542172/f65a4fc0-9620-11e6-92bd-bc1f15c95f44.png)

and expand when clicked on:
![screen shot 2016-10-19 at 5 25 24 pm](https://cloud.githubusercontent.com/assets/759581/19542189/0bf7457c-9621-11e6-86c5-87771ee7c555.png)

Can this functionality be added to googleVis?

Thank you!
Steven

**Comment by mages** [comment]
Have you looked into the newer gvisAnnotationChart function? 

Google has replaced the old Flash based annotated time line chart with this newer HTML5 version: https://developers.google.com/chart/interactive/docs/gallery/annotationchart
