### ISSUE TITLE
Changing icons

### ISSUE THREAD

**Issue by paulvern** [mages/googleVis#55]
Can you please give me a sample code to change the standard icons in gvisMap to custom icons (for example this: https://d30y9cdsu7xlg0.cloudfront.net/png/25853-200.png)? I've tried a lot of different input formats as options but It seems nothing will show when changing the standard pins to a custom image (the map simply doesn't draw). Thank you very much.

**Comment by mages** [comment]
Here is an example:
```s
library(googleVis)
df <- data.frame(Adress=c("EC3M 7HA", "東京都新宿区北新宿2-21-1"),
                 Tip=c("Lloyd's", "Tokyo R User Group"))
plot(gvisMap(df, "Adress", "Tip",
             options=list(mapType='normal',
                          icons="{'default': {'normal': 'http://icons.iconarchive.com/icons/icons-land/vista-map-markers/48/Map-Marker-Ball-Azure-icon.png',
                                               'selected': 'http://icons.iconarchive.com/icons/icons-land/vista-map-markers/48/Map-Marker-Ball-Right-Azure-icon.png'}
                                  }", width=800, height=250)))
```

**Comment by paulvern** [comment]
This is the result for me: no pins at all.
Is there something wrong in my network?

![google](https://cloud.githubusercontent.com/assets/4972498/23064011/06bf02f6-f50e-11e6-95d2-0712a2955ba3.jpg)

**Comment by mages** [comment]
I guess so, as this is what I see (note the pin icons in England and Japan):
![screenshot](https://cloud.githubusercontent.com/assets/1146581/23064269/05c71412-f507-11e6-85b2-10afa3c64d12.png)

**Comment by paulvern** [comment]
I changed the address of the icon to another one and now it works. Definitely something was blocked by our proxy. Thank you very much. Is there any option to show points as heat maps as you can do with google fusion tables?

**Comment by mages** [comment]
I am not aware of it. I think, the Google Charts Forum is the best place to seek advice: https://groups.google.com/forum/#!forum/google-visualization-api
