### ISSUE TITLE
Character limit for strings/categorical variables?

### ISSUE THREAD

**Issue by tomfbush** [mages/googleVis#56]
Hi there -- awesome library, thanks! :)

Just wanted to check -- it seems that across a few of the chart types (and table) that I have tried, there is an arbitrary character limit of 19 for categorical data -- is anyone else experiencing this?

One of my use cases is to print longer strings vs a few metrics and sometimes it would be handy to see more of the original string!

**Comment by mages** [comment]
This question is best asked on the Google Chart API Forum: https://groups.google.com/forum/#!forum/google-visualization-api
