### ISSUE TITLE
Color based on variable for gvisHistogram

### ISSUE THREAD

**Issue by ericbrownaustin** [mages/googleVis#60]
I have some data where COL1 is character, COL2 is numeric and COL3 is a logical.

I would like to create a histogram using COL1 and COL2 as my data but would like to show different colors for my individual values using COL3.  Is this possible?

**Comment by mages** [comment]
You will have to reorganise your data, so that COL1, COL2 and COL3 represent the different data sets of _numeric_ values.  

Here is the example from the help file:
```s
set.seed(123)
dat=data.frame(A=rpois(100, 20), 
               B=rpois(100, 5), 
               C=rpois(100, 50))
hist3 <- gvisHistogram(dat, options=list(
                       legend="{ position: 'top', maxLines: 2 }",
                       colors="['#5C3292', '#1A8763', '#871B47']"))

plot(hist3)
```
