### ISSUE TITLE
List of colors

### ISSUE THREAD

**Issue by elbamos** [mages/googleVis#61]
Is there a way to assert greater control over the way the interface lets the user select data, in particular the colors? 

I have a dataset with two "type" columns.  One of them is more specific than the other -- i.e., there are 5 classes in one column, and 50 in the other.  

I'd like to be able to display the class using color.  And I'd like to be able to switch between the more general view and the more specific one. 

If I set `colorvar = "moregeneralcolumn"`, then the more general column displays nicely as the color.  The interface shows 5 rows, where each shows a color and a text label.

If I then use the interface to switch to the less general column, however, the interface shows five rows of colors --- and there is no way to scroll or otherwise access the other 45 classes. 

If I set `colorvar = "lessgeneralcolumn"`, then the less general column displays poorly. It's shows a palette of all 45 colors, but without labels.  

If I then use the interface to switch to the more general column, then I see five rows with the five colors, but still no labels. 

What I'd like, is to always have rows, where its the color and a label, and a scroll bar appears if there are too many to fit (or that part of the interface could expand and take up some of the space now taken by the id picker). 

Is there any way to do that?

Thanks!

**Comment by mages** [comment]
Which googleVis function are your referring to? There is no control on the colours for the motion chart. Visit the Google documentation for more details: https://developers.google.com/chart/interactive/docs/gallery/motionchart
