### ISSUE TITLE
Docs link broken/typo?

### ISSUE THREAD

**Issue by zx8754** [mages/googleVis#68]
- rdocumentation.org

https://www.rdocumentation.org/packages/googleVis/versions/0.6.0/topics/gvisCalendar

> References
> Google Chart Tools API: http://developers.google.com/chart/interactive/docs/gallery/Calendar

Should be:
http://developers.google.com/chart/interactive/docs/gallery/calendar

- same on cran manual:

> list of configuration options, see:
> https://developers.google.com/chart/interactive/docs/gallery/Calendar#Configuration_Options
 
Should be:
https://developers.google.com/chart/interactive/docs/gallery/calendar#Configuration_Options

**Comment by mages** [comment]
Thanks for reporting the typo.  Fixed.
