### ISSUE TITLE
Chart data not showing (even when hosted)

### ISSUE THREAD

**Issue by ashenkin** [mages/googleVis#76]
I've deployed a motion chart, but the data is only showing up when accessing from via internet explorer.  I've tried FF & Chrome, neither of which seem to work.  Any thoughts?

The chart can be seen here:
http://users.ox.ac.uk/~cenv0348/light_profiles/gvis_string.html

Thanks much...

**Comment by mages** [comment]
Please see section 2.4 at the top of page 17 of the package vignette: https://cran.r-project.org/web/packages/googleVis/vignettes/googleVis.pdf

**Comment by ashenkin** [comment]
thanks @mages.  For some reason, chrome was not asking to run flash.  When i go in and set chrome to always run flash on the site, it works.  The same issue occurs on both my comps... not sure what the root of the problem is...

**Comment by mages** [comment]
Not sure, but see there: https://support.google.com/chrome/answer/6258784 <https://support.google.com/chrome/answer/6258784>
