### ISSUE TITLE
adding multiple color axes to gvisGeoChart

### ISSUE THREAD

**Issue by tiannanz** [mages/googleVis#79]
Goal: add multiple color axes to gvisGeoChart to have different groupings, 

Example: to show % coverage of some vaccine for each country within a certain income bracket, with % coverage shown by % darkness,  and income groups annotated by different color schemes.  This example would yield three single-color axes. 

I am very new to this so please let me know if I am missing something here.
Thank you.

**Comment by mages** [comment]
Unfortunately, according to the [Google documentation for Geo Charts](https://google-developers.appspot.com/chart/interactive/docs/gallery/geochart), I don't think this option is currently supported.

**Comment by tiannanz** [comment]
Thank you @mages . Hope there will be future updates on this.
