### ISSUE TITLE
gvisAnnotatedTimeLine display aggregated trend on "RangeSelector"

### ISSUE THREAD

**Issue by KathyGCY** [mages/googleVis#80]
@mages @All,

For the last example in the [googleVis Examples](https://cran.r-project.org/web/packages/googleVis/vignettes/googleVis_examples.html) is an "Annotated time line chart"
It looks like below:

<img width="864" alt="screen shot 2018-09-21 at 3 25 29 pm" src="https://user-images.githubusercontent.com/14912791/45901898-9ebfd300-bdb2-11e8-8eb5-5bcb9df81d83.png">

My Question about the lower part of the chart where there's a little "curtain" that I could use to select range to view. Is it possible that I show aggregated value in this part, instead of showing it for only one of many sequences?

Thanks!

All the best,
Kathy

**Comment by mages** [comment]
I don’t think so. Check the documentation on Google Charts for more details.
