### ISSUE TITLE
BubbleChart with Fruits data, including a gradient color scale

### ISSUE THREAD

**Issue by martinschmelzer** [mages/googleVis#81]
Using the following code

```
library(googleVis)
Bubble <- gvisBubbleChart(Fruits, idvar="Fruit", 
                          xvar="Sales", yvar="Expenses",
                          colorvar="Profit", 
                          options=list(
                            colorAxis="{colors: ['yellow', 'red']}",
                            hAxis='{minValue:75, maxValue:125}'))
plot(Bubble)
```

I intend to create a chart where the Profit column of the Fruits data is mapped to a gradient color scale from yellow to red. But the result does not show the gradient color scale. Somehow, in the JS output, the Profit column is of type string (in contrast to the R dataframe column) which prevents the gradient scale to be applied:

```
function gvisDataBubbleChartIDf63b69c63e04 () {
var data = new google.visualization.DataTable();
var datajson = [
                ["Apples", 98, 78, "20"],
                ["Oranges", 96, 81, "15"],
                ["Bananas", 85, 76, "9"]
               ];

/* ... SKIPPED SOME ROWS ... */
data.addColumn('string',' Profit');
data.addRows(datajson);
return(data);
}
```

Not sure if this is a bug?

**Comment by mages** [comment]
Yes, you are correct. Only character value were allowed for `colorvar`. I have updated this now to allow for either character or numeric values. Your example produces a gradient colour scale with the developer version of googleVis on GitHub.

**Comment by martinschmelzer** [comment]
Great! Thanks for solving this that quick!
