### ISSUE TITLE
Error: "Tried to unbox a vector of length 3" when I use gvisTreeMap in Shiny

### ISSUE THREAD

**Issue by APonce73** [mages/googleVis#82]
I tried to run gvisTreeMap in Shiny. When I used outside of shiny is not problem... work well! But when I tried to use it with shiny with "renderGvis" I have the next message:

<img width="617" alt="screen shot 2019-02-07 at 11 50 15" src="https://user-images.githubusercontent.com/3358069/52431841-a3b9c080-2ace-11e9-88c5-48f732eff306.png">

Here the server.R
#######
library(tidyverse)
library(shiny)
library(googleVis)
library(RColorBrewer)

#mx.states1 <- read.table("~/Dropbox/Shiny1/Tabla.txt", header = T)

# Define server logic for slider examples
shinyServer(function(input, output, session) {
 
  output$Treeplot1 <- renderGvis({
    
    #Feynmann1 <- mx.states1
    Feynmann1 <- mx.states1 %>%
      select(Estado, parent, Valor) %>%
      mutate(Valor1 = Valor)
    
    Treeplot11 <- gvisTreeMap(Feynmann1,  
                         options = list(width = 1000, height = 800,
                                        fontSize = 18,
                                        minColor = '#F7FBFF',
                                        midColor = '#FD8D3C',
                                        maxColor = '#800026',
                                        headerHeight = 20,
                                        fontColor = c('black','black','white'),
                                        showScale = TRUE))
    return(Treeplot11)   
  })
   

#######
#Here de ui.R

library(tidyverse)
library(shiny)
library(knitr)
library(plotly)
library(googleVis)

shinyUI(navbarPage(
  title = "",

    tabPanel('Local leanguage', 
           shinyUI(fluidPage(
             #Application title
             titlePanel("Maize in different Leanguage"),
                 width = 1)),       
               fluidRow(
                 column(9,
                        htmlOutput("Treeplot1", width = "1000", height = "600"))
               ))
))

The file that I used is this one: 

[Tabla.txt](https://github.com/mages/googleVis/files/2842079/Tabla.txt)

I hope that you can give me a tip!!! 

Here my sessioninfo()
<img width="599" alt="screen shot 2019-02-07 at 11 58 38" src="https://user-images.githubusercontent.com/3358069/52432305-c00a2d00-2acf-11e9-918a-8784713eed23.png">

Alex

**Comment by mages** [comment]
The way you specify the textStyle options are not correct. The following works for me:

```r
Treeplot11 <- gvisTreeMap(
  Feynmann1, idvar = "Estado", parentvar ="parent",
  sizevar = "Valor", colorvar = "Valor1",
  options = list(width = 1000, height = 800,
                 textStyle = "{fontSize:18, fontColor:['black', 'black', 'white']}",
                 minColor = '#F7FBFF',
                 midColor = '#FD8D3C',
                 maxColor = '#800026',
                 headerHeight = 20,
                 showScale = TRUE))
```

**Comment by APonce73** [comment]
Many many many thanks!!!
Now works perfectly!!!
Gracias (Thanks a lot!!!!!)

**Comment by mages** [comment]
You are welcome.
