### ISSUE TITLE
gVisOrgChart not displaying child nodes

### ISSUE THREAD

**Issue by prabhjot0509** [mages/googleVis#84]
Hi,

I have been trying to plot a gVisOrgChart but some child nodes are not visible in the final output even though they exist in the data. Is there a maximum size of characters that child nodes can hold in the Output ?

Below is the data i am using

![image](https://user-images.githubusercontent.com/22430958/55702751-2be81380-59f5-11e9-96d3-8e45e39809ec.png)

Below is my Code

Org <- gvisOrgChart(Test4, idvar = "Name", parentvar = "Supervisor_Employee_Code",
                 tipvar="Position_Text_Augmented",
                 options=list(width= '800', height= '800',
                              size='medium', allowCollapse=TRUE))
plot(Org)

Below is the screenshot of the output

![image](https://user-images.githubusercontent.com/22430958/55702812-618cfc80-59f5-11e9-95f7-7ea046af339d.png)

I have tried adjusting the width of the nodes as well but still not able to visualize the complete output.

**Comment by mages** [comment]
I believe there is an issue with your data. 

The following works for me:
```r
dat <- data.frame(Parent=c(NA, rep("A", 20)),
                  Child=c("A", 1:20),
                  Val=1:21)
library(googleVis)
plot(gvisOrgChart(dat, idvar = "Child", 
             parentvar = "Parent", 
             tipvar="Val"))
```
![Screenshot 2019-04-09 at 19 01 46](https://user-images.githubusercontent.com/1146581/55811312-fe38c280-5af9-11e9-922a-cb83f0dd260e.png)
