### ISSUE TITLE
Charts are not loading

### ISSUE THREAD

**Issue by mubashirqasim** [mages/googleVis#89]
Hi there,

Just a heads up... 

For some reason, none of the charts are loading on the following website or on my shiny app:

https://cran.r-project.org/web/packages/googleVis/vignettes/googleVis_examples.html

It might be due to missing js file:

![image](https://user-images.githubusercontent.com/8086373/84717739-da5cf080-afca-11ea-8469-39db0b0ff60c.png)

Cheers.

**Comment by mages** [comment]
Thanks for reporting this issue. I have updated the link to the Google JavaScript function. Can you please test with googleVis 0.6.6 from GitHub.

**Comment by beansrowning** [comment]
I am also encountering this issue (though it may be for a different reason).  

I'm on 0.6.6, R Version 4.0.1.  

If I print a viz with `tag = NULL` or `tag="html"`, the chart normally pops up. 

If I try and embed the figure in an Rmarkdown document using `tag = "chart"`, the chart does not render.
Trying to run the viz function from the DOM also fails:

```js
gvisDataTreeMapID23246cc47a7d()
#> exploration.html:461 Uncaught TypeError: Cannot read property 'DataTable' of undefined
#>    at gvisDataTreeMapID23246cc47a7d (exploration.html:461)
#>    at <anonymous>:1:1
```

**Comment by mages** [comment]
Thanks for your comment. It seems the line `<script type="text/javascript\" src="https://www.google.com/jsapi?callback=displayChart%s"></script>` which is generated by the `plot` or `print` calls is replaced in the rendering process with the actual content of https://www.google.com/jsapi?callback 
I am not sure if this is due to changes in knitr, rmarkdown or pandoc.

**Comment by mages** [comment]
Setting the option `self_contained` to `false` in the YAML header of the RMarkdown file seems to resolve the issue:

```
output:
  html_document:
    self_contained: false
```

**Comment by mages** [comment]
New version of googleVis 0.6.6 CRAN, with the vignettes showing the charts again: https://cran.r-project.org/web/packages/googleVis/index.html
