### ISSUE TITLE
gvisGauge from googleVis package in R studio

### ISSUE THREAD

**Issue by ZinebHasnaoui** [mages/googleVis#90]
I am using gvisGauge function on R studio, can I change the needle red color to black?

**Comment by mages** [comment]
Yes, you can:
```r
library(googleVis)
plot(gvisGauge(CityPopularity, options=list(min=0, max=800, greenFrom=500,
                     greenTo=800, yellowFrom=300, yellowTo=500,
                     redFrom=0, redTo=300, redColor="#000000")))
```
For more details visit the Google documentation: https://developers.google.com/chart/interactive/docs/gallery/gauge

**Comment by ZinebHasnaoui** [comment]
thank you for responding, but your code changes the red part on the gauge to black, not the needle. is it possible to change the needle color to black?

**Comment by mages** [comment]
Sorry, I misread your question. No, unfortunately there is no option to change the colour of the needle.
