### ISSUE TITLE
Allow to define custom (HTML) tooltips in gvisGeoChart

### ISSUE THREAD

**Issue by durey** [mages/googleVis#93]
It is totally possible with the Google Javascript library. AFAIK, we just can't do it using googleVis. Would it be too hard to include it?

**Comment by durey** [comment]
@mages , would you take a pull request into account if I create one for this?

**Comment by mages** [comment]
Sure. Do you have a live example? This is different to [tooltips via roles](https://cran.r-project.org/web/packages/googleVis/vignettes/googleVis_intro.html#using-roles-via-googlevis)?

**Comment by durey** [comment]
Is exactly the same. The thing is, they just don't work in gvisGeoChart.
I will try to look into it and propose a fix as soon as possible, then!

**Comment by mages** [comment]
Fixed with https://github.com/mages/googleVis/pull/94. Version 0.6.10 of googleVis is on its way to CRAN.
