### ISSUE TITLE
Change the chartArea background color of gvisAnnotationChart

### ISSUE THREAD

**Issue by gd047** [mages/googleVis#98]
How to change the chartArea background color of gvisAnnotationChart?
I tried this but didn't work

```
gvisAnnotationChart(
...,
options = list(
    ...,
    chart = list(
      backgroundColor = "#D3D3D3"
    )
  )
)
```

**Comment by mages** [comment]
Unfortunately, the Google chart API doesn't have an option to change the background colour: https://developers.google.com/chart/interactive/docs/gallery/annotationchart

**Comment by gd047** [comment]
I think that it can be done. See [this answer](https://stackoverflow.com/a/39138141/170792)

**Comment by mages** [comment]
It is not officially supported by Google. I suggest you ask the Google developers directly on the Google Chart API Forum: https://groups.google.com/g/google-visualization-api

**Comment by gd047** [comment]
That's the way https://stackoverflow.com/a/71739376/299077

**Comment by mages** [comment]
That's great news! I shall include into the examples go gvisAnnotationChart
